apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch-logging
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
spec:
  backend:
    serviceName: elasticsearch-logging
    servicePort: 9200
